spring:
  application:
    name: SpringRedisCache
  cache:
    type: redis
    redis:
      time-to-live: 36000
  data:
    redis:
      host: localhost
      port: 6379
      password: 1qaz!QAZ

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://0.0.0.0:5432/cacheablestore
    username: fluxdb
    password: fluxdbpwd

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true
